In [27]:
import pandas as pd
import matplotlib.pyplot as plt

In [28]:
df_unidades_curso = pd.read_csv('../unidades_academicas/unidades_e_cursos.csv', sep=';')
df_tccs = pd.read_csv('../TCC/tccs_tratado3.0.csv', sep=';')
df_pesquisa = pd.read_csv('../projetos-de-pesquisa-limpo2.0.csv')

In [29]:
df_unidades_curso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   curso    1200 non-null   object
 1   unidade  1200 non-null   object
dtypes: object(2)
memory usage: 18.9+ KB

In [30]:
df_tccs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84893 entries, 0 to 84892
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   titulo           84893 non-null  object
 1   nome_autor       84893 non-null  object
 2   nome_orientador  84893 non-null  object
 3   curso            84893 non-null  object
 4   nivel            84893 non-null  object
 5   tipo_trabalho    67045 non-null  object
 6   ano              84893 non-null  float64
 7   data_defesa      84893 non-null  object
 8   classificacao    84893 non-null  object
dtypes: float64(1), object(8)
memory usage: 5.8+ MB

In [31]:
df_pesquisa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21382 entries, 0 to 21381
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              21382 non-null  int64
 1   id_projeto_pesquisa     21382 non-null  int64
 2   codigo_projeto          21382 non-null  object
 3   titulo                  21382 non-null  object
 4   palavras_chave          21130 non-null  object
 5   id_projeto              21382 non-null  int64
 6   ano                     21382 non-null  int64
 7   data_inicio             21351 non-null  object
 8   data_fim                21121 non-null  object
 9   situacao                21382 non-null  object
 10  tipo_projeto            21382 non-null  object
 11  categoria_projeto       21382 non-null  object
 12  id_unidade              21382 non-null  int64
 13  unidade                 21382 non-null  object
 14  id_grupo_pesquisa       17636 non-null  float64
 15  grupo_pesquisa          17597 non-null  object
 16  linha_pesquisa          20721 non-null  object
 17  area_conhecimento_cnpq  20971 non-null  object
 18  classificacao           21382 non-null  object
dtypes: float64(1), int64(5), object(13)
memory usage: 3.1+ MB

In [32]:
for df in [df_unidades_curso, df_tccs]:
    df["curso"] = (df["curso"] #padronizar
                   .astype(str)
                   .str.strip()
                   .str.lower()
                   .str.normalize("NFKD")
                   .str.encode("ascii", errors="ignore")
                   .str.decode("utf-8"))

df_temp = pd.merge(df_tccs, df_unidades_curso, on="curso", how="outer")

df_temp.head()

,titulo,nome_autor,nome_orientador,curso,nivel,tipo_trabalho,ano,data_defesa,classificacao,unidade
0,NaN,NaN,NaN,aaa,NaN,NaN,NaN,NaN,NaN,"FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOC..."
1,explorando o potencial das finanças verdes: um...,ana flavia eufrasio de lima,israel josé dos santos felipe,administracao,graduação,monografia,2024.0,2025/11/25 00:00:00.000,tcc,CENTRO DE CIÊNCIAS SOCIAIS APLICADAS
2,explorando o potencial das finanças verdes: um...,ana flavia eufrasio de lima,israel josé dos santos felipe,administracao,graduação,monografia,2024.0,2025/11/25 00:00:00.000,tcc,"FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOC..."
3,indicadores de desempenho: um estudo da perspe...,alvaro araujo de medeiros,marconi neves macedo,administracao,graduação,monografia,2025.0,2025/09/09 00:00:00.000,tcc,CENTRO DE CIÊNCIAS SOCIAIS APLICADAS
4,indicadores de desempenho: um estudo da perspe...,alvaro araujo de medeiros,marconi neves macedo,administracao,graduação,monografia,2025.0,2025/09/09 00:00:00.000,tcc,"FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOC..."

In [33]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102825 entries, 0 to 102824
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   titulo           102139 non-null  object
 1   nome_autor       102139 non-null  object
 2   nome_orientador  102139 non-null  object
 3   curso            102825 non-null  object
 4   nivel            102139 non-null  object
 5   tipo_trabalho    83908 non-null   object
 6   ano              102139 non-null  float64
 7   data_defesa      102139 non-null  object
 8   classificacao    102139 non-null  object
 9   unidade          102480 non-null  object
dtypes: float64(1), object(9)
memory usage: 7.8+ MB

In [34]:
df_temp2 = pd.merge(df_pesquisa, df_unidades_curso, on="unidade", how="outer")

df_temp2.head(50)

,Unnamed: 0,id_projeto_pesquisa,codigo_projeto,titulo,palavras_chave,id_projeto,ano,data_inicio,data_fim,situacao,tipo_projeto,categoria_projeto,id_unidade,unidade,id_grupo_pesquisa,grupo_pesquisa,linha_pesquisa,area_conhecimento_cnpq,classificacao,curso
0,5634.0,97708168.0,PVD7269-2013,Diagnóstico das ações e programas de alimentaç...,"Alimentação, Nutrição, Políticas Públicas de S...",91795694.0,2013.0,2013-08-01,2014-07-31,FINALIZADO,INTERNO,Pesquisa Científica,5906.0,0576/2011 - AÇÕES DE ALIMENTAÇÃO E NUTRIÇÃO NA...,107.0,"ALIMENTOS, NUTRIÇÃO E SAÚDE","Diagnóstico, Análise e Intervenção Nutricional...",Saúde Pública,pesquisa,NaN
1,7343.0,90959569.0,PVD7269-2012,Diagnóstico das ações e programas de alimentaç...,"Alimentação, Nutrição, Políticas Públicas de S...",90959549.0,2012.0,2012-02-01,2013-01-31,RENOVADO,INTERNO,Pesquisa Científica,5906.0,0576/2011 - AÇÕES DE ALIMENTAÇÃO E NUTRIÇÃO NA...,107.0,"ALIMENTOS, NUTRIÇÃO E SAÚDE","Diagnóstico, Análise e Intervenção Nutricional...",Saúde Pública,pesquisa,NaN
2,9031.0,85143932.0,PVD7269-2011,Diagnóstico das ações e programas de alimentaç...,"Alimentação, Nutrição, Políticas Públicas de S...",85143892.0,2011.0,2011-08-01,2013-07-31,RENOVADO,INTERNO,Pesquisa Científica,5906.0,0576/2011 - AÇÕES DE ALIMENTAÇÃO E NUTRIÇÃO NA...,107.0,"ALIMENTOS, NUTRIÇÃO E SAÚDE","Diagnóstico, Análise e Intervenção Nutricional...",Saúde Pública,pesquisa,NaN
3,955.0,121494695.0,PIA13918-2017,Produção de biomassa algácea com alto teor de...,"Microalgas, biomassa, biocombustivel",91811779.0,2017.0,2017-01-02,2020-07-30,FINALIZADO,EXTERNO,Pesquisa Científica,176.0,ADMINISTRAÇÃO DO CB,NaN,NaN,Biocombustiveis x aquicultura,Tecnologia e Inovação,pesquisa,NaN
4,3129.0,110151780.0,PVB12064-2015,CALIBRAÇÃO DO MÉTODO DE HARGREAVES PARA OBTENÇ...,"Evapotranspiração de referência, FAO-56 Penman...",91804531.0,2015.0,2015-08-01,2018-07-31,RENOVADO,INTERNO,Pesquisa Científica,119.0,ADMINISTRAÇÃO DO CCET,123452618.0,Grupo de Estudos Observacionais e de Modelagem...,Agrometeorologia e Agroclimatologia do Nordest...,Meteorologia Aplicada,pesquisa,NaN
5,3134.0,110264841.0,PVB12150-2015,MODELO PARA ESTIMAR A IRRADIÂNCIA GLOBAL COM B...,"Radiação Solar, Modelos Empíricos, Temperatura...",91804694.0,2015.0,2015-08-01,2017-07-31,RENOVADO,INTERNO,Pesquisa Científica,119.0,ADMINISTRAÇÃO DO CCET,123452618.0,Grupo de Estudos Observacionais e de Modelagem...,Agrometeorologia e Agroclimatologia do Nordest...,Meteorologia Aplicada,pesquisa,NaN
6,3686.0,103980188.0,PIB11264-2014,CALIBRAÇÃO DO MÉTODO DE HARGREAVES PARA OBTENÇ...,"Evapotranspiração de referência, FAO-56 Penman...",91800534.0,2014.0,2014-08-01,2015-07-31,FINALIZADO,INTERNO,Pesquisa Científica,119.0,ADMINISTRAÇÃO DO CCET,11677560.0,"Clima, Ambiente, Saúde e Educação",Agrometeorologia,Meteorologia Aplicada,pesquisa,NaN
7,7044.0,91866880.0,PVB8966-2012,Gestão Tecnológica do Núcleo de Processamento ...,"NUPPRAR, Gestão tecnológica, Serviços tecnológ...",91791957.0,2012.0,2012-08-02,2016-10-06,EM EXECUÇÃO,EXTERNO,Pesquisa Tecnológica,119.0,ADMINISTRAÇÃO DO CCET,83.0,ELETROQUÍMICA E CORROSÃO,ÁREA TECNOLÓGICA DE PROCESSAMENTO E MEDIÇÃO DE...,Eletroquímica,pesquisa,NaN
8,6017.0,97503230.0,PVG5255-2013,Análise Comparativa entre Estratégias de Contr...,"Controle Adaptativo, Sistemas com Estrutura Va...",91795472.0,2013.0,2013-08-01,2014-07-31,EM EXECUÇÃO,INTERNO,Pesquisa Científica,4524.0,AGÊNCIA DE INOVAÇÃO - AGIR,31.0,AUTOMAÇÃO INDUSTRIAL E CONTROLE DE PROCESSOS,Automação Industrial e Controle de Processos,"Controle de Processos Eletrônicos, Retroalimen...",pesquisa,NaN
9,7678.0,90860914.0,PVG5255-2012,Análise Comparativa entre Estratégias de Contr...,"Controle Adaptativo, Sistemas com Estrutura Va...",90860903.0,2012.0,2012-08-01,2013-07-31,RENOVADO,INTERNO,Pesquisa Científica,4524.0,AGÊNCIA DE INOVAÇÃO - AGIR,31.0,AUTOMAÇÃO INDUSTRIAL E CONTROLE DE PROCESSOS,Automação Industrial e Controle de Processos,"Controle de Processos Eletrônicos, Retroalimen...",pesquisa,NaN
10,9318.0,85071868.0,PVG5255-2011,Análise Comparativa entre Estratégias de Contr...,"Controle Adaptativo, Sistemas com Estrutura Va...",85071857.0,2011.0,2011-08-01,2012-07-31,RENOVADO,INTERNO,Pesquisa Científica,4524.0,AGÊNCIA DE INOVAÇÃO - AGIR,31.0,AUTOMAÇÃO INDUSTRIAL E CONTROLE DE PROCESSOS,Automação Industrial e Controle de Processos,"Controle de Processos Eletrônicos, Retroalimen...",pesquisa,NaN
11,11341.0,2395918.0,PVG5255-2010,Análise Comparativa entre Estratégias de Contr...,"Controle Adaptativo, Sistemas com Estrutura Va...",2395916.0,2010.0,2010-08-01,2011-07-31,RENOVADO,INTERNO,Pesquisa Científica,4524.0,AGÊNCIA DE INOVAÇÃO - AGIR,31.0,AUTOMAÇÃO INDUSTRIAL E CONTROLE DE PROCESSOS,Automação Industrial e Controle de Processos,"Controle de Processos Eletrônicos, Retroalimen...",pesquisa,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ALUNOS ESPECIAIS PPG - RESIDENCIA,NaN,NaN,NaN,NaN,NaN,residencia alunos especiais ppg
13,11030.0,2054706.0,PVE2934-2010,Análise Webométrica dos Sítios das Universidad...,"Webometria, Estudos métricos da informação, in...",2054677.0,2010.0,2010-02-06,2011-02-05,FINALIZADO,EXTERNO,Pesquisa Científica,21.0,BIBLIOTECA CENTRAL ZILA MAMEDE,5242392.0,INFORMAÇÃO NA SOCIEDADE CONTEMPORÂNEA,Estudos Métricos da Informação em CT&I,Ciência da Informação,pesquisa,NaN
14,11031.0,2054854.0,PVE2935-2010,Análise webométrica dos sítios das instituiçõe...,"Estudos Métricos da Informação, Webometria, Ci...",2054805.0,2010.0,2010-02-06,2011-02-05,FINALIZADO,EXTERNO,Pesquisa Científica,21.0,BIBLIOTECA CENTRAL ZILA MAMEDE,5242392.0,INFORMAÇÃO NA SOCIEDADE CONTEMPORÂNEA,Estudos Métricos da Informação em CT&I,Ciência da Informação,pesquisa,NaN
15,12709.0,11146683.0,PVE2934-2009,Análise Webométrica dos Sítios das Universidad...,"Webometria, Estudos métricos da informação, in...",11146683.0,2009.0,2008-04-29,2009-10-29,RENOVADO,EXTERNO,Pesquisa Científica,21.0,BIBLIOTECA CENTRAL ZILA MAMEDE,5242392.0,INFORMAÇÃO NA SOCIEDADE CONTEMPORÂNEA,Estudos Métricos da Informação em CT&I,Ciência da Informação,pesquisa,NaN
16,12710.0,11150810.0,PVE2935-2009,Análise webométrica dos sítios das instituiçõe...,"Estudos Métricos da Informação, Webometria, Ci...",11150810.0,2009.0,2007-12-01,2009-11-30,RENOVADO,EXTERNO,Pesquisa Científica,21.0,BIBLIOTECA CENTRAL ZILA MAMEDE,5242392.0,INFORMAÇÃO NA SOCIEDADE CONTEMPORÂNEA,Estudos Métricos da Informação em CT&I,Ciência da Informação,pesquisa,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAENE,NaN,NaN,NaN,NaN,NaN,mundo digital para a educacao de surdo
18,5019.0,106489617.0,PIP11780-2013,ACERTA: Avaliação de Crianças Em Risco de Tran...,"dislexia, discalculia, aprendizagem",91801896.0,2013.0,2013-01-04,2016-12-30,EM EXECUÇÃO,EXTERNO,Pesquisa Científica,5229.0,CAMPUS DO CÉREBRO,117009255.0,Linguagem e Processos Cognitivos,Aprendizagem e Cognição,Ensino-Aprendizagem,pesquisa,NaN
19,3887.0,100961653.0,PVA10786-2014,METODOLOGIAS ATIVAS COMO FERRAMENTA DE MELHORI...,"Educação, ensino-aprendizagem em bioquímica, b...",91798348.0,2014.0,2014-01-01,2016-07-31,RENOVADO,INTERNO,Pesquisa Científica,185.0,CB - COORDENAÇÃO DO CURSO DE CIÊNCIAS BIOLÓGIC...,158795479.0,Pesquisa e Inovação em Ensino de Bioquímica,Métodos ativos e inovadores para o ensino de b...,Proteínas,pesquisa,NaN
20,7045.0,2243118.0,PVB8985-2012,IMPLANTAÇÃO DO SISTEMA DE QUALIDADE NA CENTRAL...,"Boas praticas de laboratório (BPL), ISO/IEC 17...",2243116.0,2012.0,2012-10-03,2013-02-03,EM EXECUÇÃO,EXTERNO,Pesquisa Tecnológica,4663.0,CCET - NÚCLEO DE ESTUDOS EM PETRÓLEO E GÁS NAT...,83.0,ELETROQUÍMICA E CORROSÃO,Química Ambiental,Análise de Traços e Química Ambiental,pesquisa,NaN
21,8519.0,86182621.0,PVB4873-2011,DIAGNÓSTICO E MONITORAMENTO DA QUALIDADE DA ÁG...,"Monitoramento, água, sedimento, paramentro fis...",86182586.0,2011.0,2011-08-09,2012-03-30,EM EXECUÇÃO,EXTERNO,Pesquisa Tecnológica,4663.0,CCET - NÚCLEO DE ESTUDOS EM PETRÓLEO E GÁS NAT...,83.0,ELETROQUÍMICA E CORROSÃO,Análise de Traço e química ambiente,Análise de Traços e Química Ambiental,pesquisa,NaN
22,8582.0,85798248.0,PVB7358-2011,ANÁLISE QUÍMICAS EM FLUÍDOS DE CORROSÃO E INCR...,"Analises quimicas, fluidos, residuos, validaca...",85798246.0,2011.0,2011-08-01,2013-07-01,EM EXECUÇÃO,EXTERNO,Pesquisa Tecnológica,4663.0,CCET - NÚCLEO DE ESTUDOS EM PETRÓLEO E GÁS NAT...,83.0,ELETROQUÍMICA E CORROSÃO,Metais traços em amostras ambientais,Análise de Traços e Química Ambiental,pesquisa,NaN
23,10334.0,2220908.0,PVB4873-2010,DIAGNÓSTICO E MONITORAMENTO DA QUALIDADE DA ÁG...,"Monitoramento, água, sedimento, paramentro fis...",2220906.0,2010.0,2010-04-01,2012-04-01,RENOVADO,EXTERNO,Pesquisa Tecnológica,4663.0,CCET - NÚCLEO DE ESTUDOS EM PETRÓLEO E GÁS NAT...,83.0,ELETROQUÍMICA E CORROSÃO,Análise de Traço e química ambiente,Análise de Traços e Química Ambiental,pesquisa,NaN
24,10559.0,2315085.0,PVC5026-2010,INVESTIGAÇÃO DO FUNCIONAMENTO NEUROCOGNITIVO D...,neuropsicologia do desenvolvimento; tumores ce...,2315083.0,2010.0,2009-08-01,2011-08-01,FINALIZADO,EXTERNO,Pesquisa Científica,5050.0,CCHLA - JORNADA DE MEMÓRIAS,118.0,GRUPO DE ESTUDOS PSICOLOGIA E SAÚDE - GEPPS,neuropsicologia do desenvolvimento e da aprend...,Psicologia Cognitiva,pesquisa,NaN
25,10593.0,2446250.0,PVC5505-2010,Programa de identificação de talentos para o p...,talentos; tecnologia da informação; avaliação ...,2446241.0,2010.0,2009-04-01,2012-04-01,FINALIZADO,EXTERNO,Pesquisa Científica,5050.0,CCHLA - JORNADA DE MEMÓRIAS,126.0,NÚCLEO DE ESTUDOS EM PSICOLOGIA HISTÓRICO-CULT...,Neuropsicologia do desenvolvimento e da Aprend...,"Construção e Validade de Testes, Escalas e Out...",pesquisa,NaN
26,12349.0,17775131.0,PVC4461-2010,Auta de Souza no Portal da Memória Literária P...,"Auta de Souza, cancioneiro, fortuna crítica",17774722.0,2009.0,2010-01-01,2010-12-31,EM EXECUÇÃO,INTERNO,Pesquisa Científica,5072.0,CCHLA/EXT - AUTA DE SOUZA - OBRAS REUNIDAS,NaN,NaN,"Pensamento social, sistemas de conhecimento e ...",Outras Sociologias Específicas,pesquisa,NaN
27,10692.0,17775139.0,PVD2333-2010,AVALIAÇÃO DA ASCARIDIASE EM CRIANÇAS MENORES D...,"ASCARIDIASE, CRIANÇAS, PREVALÊNCIA",17780800.0,2010.0,2010-02-01,2010-12-30,FINALIZADO,EXTERNO,Pesquisa Científica,2971.0,CCS - PROG. DE APOIO À MELHORIA DA QUAL. DO EN...,71.0,BIOANÁLISES,Doenças infecciosas e parasitárias;;;,Avaliação e analises toxicológicas,pesquisa,NaN
28,13634.0,5483968.0,PVD2333-2008,AVALIAÇÃO DA ASCARIDIASE EM CRIANÇAS MENORES D...,"ASCARIDIASE, CRIANÇAS, PREVALÊNCIA",5483968.0,2008.0,2008-08-23,2009-07-23,RENOVADO,EXTERNO,Pesquisa Científica,2971.0,CCS - PROG. DE APOIO À MELHORIA DA QUAL. DO EN...,71.0,BIOANÁLISES,Doenças infecciosas e parasitárias;;;,Avaliação e analises toxicológicas,pesquisa,NaN
29,5855.0,97839885.0,PVE5402-2013,APLs intensivos em cultura e o desenvolvimento...,Arranjos Produtivos Locais. Cultura. Desenvol...,91796033.0,2013.0,2013-08-01,2014-07-31,EM EXECUÇÃO,INTERNO,Pesquisa Científica,1616.0,CCSA VICE-DIRETORIA,13074760.0,"Grupo de estudos e pesquisa em espaço, trabalh...",Inovação e Desenvolvimento,Organização Industrial e Estudos Industriais,pesquisa,NaN
30,7536.0,90968227.0,PVE5402-2012,APLs intensivos em cultura e o desenvolvimento...,Arranjos Produtivos Locais. Cultura. Desenvol...,90968215.0,2012.0,2012-08-01,2013-07-31,RENOVADO,INTERNO,Pesquisa Científica,1616.0,CCSA VICE-DIRETORIA,13074760.0,"Grupo de estudos e pesquisa em espaço, trabalh...",Inovação e Desenvolvimento,Organização Industrial e Estudos Industriais,pesquisa,NaN
31,9161.0,85129609.0,PVE5402-2011,APLs intensivos em cultura e o desenvolvimento...,Arranjos Produtivos Locais. Cultura. Desenvol...,85129597.0,2011.0,2011-08-01,2012-07-31,RENOVADO,INTERNO,Pesquisa Científica,1616.0,CCSA VICE-DIRETORIA,13074760.0,"Grupo de estudos e pesquisa em espaço, trabalh...",Inovação e Desenvolvimento,Organização Industrial e Estudos Industriais,pesquisa,NaN
32,11099.0,2420534.0,PVE5402-2010,APLs intensivos em cultura e o desenvolvimento...,Arranjos Produtivos Locais. Cultura. Desenvol...,2420532.0,2010.0,2010-08-01,2011-07-31,RENOVADO,INTERNO,Pesquisa Científica,1616.0,CCSA VICE-DIRETORIA,13074760.0,"Grupo de estudos e pesquisa em espaço, trabalh...",Inovação e Desenvolvimento,Organização Industrial e Estudos Industriais,pesquisa,NaN
33,5938.0,95514246.0,PVF9389-2013,A PESQUISA COMO COMPONENTE NA FORMAÇÃO DO PEDA...,"Pesquisa, formação, Pedagogia",91794154.0,2013.0,2013-01-01,2016-12-31,RENOVADO,INTERNO,Pesquisa Científica,1482.0,CENTRO DE ENSINO SUPERIOR DO SERIDÓ,8999630.0,HISTÓRIA E EDUCAÇÃO,Saberes e práticas,Métodos e Técnicas de Ensino,pesquisa,NaN
34,13852.0,5444348.0,PVF2252-2008,FAZENDO GÊNERO: um estudo sobre a carta pessoal,gêneros discursivos; carta pessoal; produção t...,5444348.0,2008.0,2008-08-01,2009-07-31,EM EXECUÇÃO,INTERNO,Pesquisa Científica,1482.0,CENTRO DE ENSINO SUPERIOR DO SERIDÓ,148.0,"GRUPO DE PESQUISA EM GESTÃO, TRABALHO E POLÍTI...",Linguagem e cognição,Lingüística Aplicada,pesquisa,NaN
35,5087.0,95486138.0,PVA613-2013,Strepsiptera do Rio Grande do Norte - Insetos...,Strepsiptera;Armadilha Malaise;entomofauna pot...,91793934.0,2013.0,2013-01-01,2013-12-31,FINALIZADO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,1.0,ISOLADO,Entomologia Agrícola;Taxonomia de Grupos Recen...,Entomologia e Malacologia de Parasitos e Vetores,pesquisa,biomedicina
36,5087.0,95486138.0,PVA613-2013,Strepsiptera do Rio Grande do Norte - Insetos...,Strepsiptera;Armadilha Malaise;entomofauna pot...,91793934.0,2013.0,2013-01-01,2013-12-31,FINALIZADO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,1.0,ISOLADO,Entomologia Agrícola;Taxonomia de Grupos Recen...,Entomologia e Malacologia de Parasitos e Vetores,pesquisa,ciencias biologicas
37,5087.0,95486138.0,PVA613-2013,Strepsiptera do Rio Grande do Norte - Insetos...,Strepsiptera;Armadilha Malaise;entomofauna pot...,91793934.0,2013.0,2013-01-01,2013-12-31,FINALIZADO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,1.0,ISOLADO,Entomologia Agrícola;Taxonomia de Grupos Recen...,Entomologia e Malacologia de Parasitos e Vetores,pesquisa,ecologia
38,5087.0,95486138.0,PVA613-2013,Strepsiptera do Rio Grande do Norte - Insetos...,Strepsiptera;Armadilha Malaise;entomofauna pot...,91793934.0,2013.0,2013-01-01,2013-12-31,FINALIZADO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,1.0,ISOLADO,Entomologia Agrícola;Taxonomia de Grupos Recen...,Entomologia e Malacologia de Parasitos e Vetores,pesquisa,engenharia de aquicultura
39,6808.0,88931516.0,PVA763-2012,Expressão de Glucagon -Like Peptide-1 (GLP-1) ...,Glicemia pós-prandial;Glucagon-Like-Peptídio 1...,88931497.0,2012.0,2012-01-01,2012-12-31,EM EXECUÇÃO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,6.0,BIOQUÍMICA DA NUTRIÇÃO,INTERAÇÃO GENE-NUTRIENTE;VALOR BIOLÓGICO DE AL...,Bioquímica da Nutrição,pesquisa,biomedicina
40,6808.0,88931516.0,PVA763-2012,Expressão de Glucagon -Like Peptide-1 (GLP-1) ...,Glicemia pós-prandial;Glucagon-Like-Peptídio 1...,88931497.0,2012.0,2012-01-01,2012-12-31,EM EXECUÇÃO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,6.0,BIOQUÍMICA DA NUTRIÇÃO,INTERAÇÃO GENE-NUTRIENTE;VALOR BIOLÓGICO DE AL...,Bioquímica da Nutrição,pesquisa,ciencias biologicas
41,6808.0,88931516.0,PVA763-2012,Expressão de Glucagon -Like Peptide-1 (GLP-1) ...,Glicemia pós-prandial;Glucagon-Like-Peptídio 1...,88931497.0,2012.0,2012-01-01,2012-12-31,EM EXECUÇÃO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,6.0,BIOQUÍMICA DA NUTRIÇÃO,INTERAÇÃO GENE-NUTRIENTE;VALOR BIOLÓGICO DE AL...,Bioquímica da Nutrição,pesquisa,ecologia
42,6808.0,88931516.0,PVA763-2012,Expressão de Glucagon -Like Peptide-1 (GLP-1) ...,Glicemia pós-prandial;Glucagon-Like-Peptídio 1...,88931497.0,2012.0,2012-01-01,2012-12-31,EM EXECUÇÃO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,6.0,BIOQUÍMICA DA NUTRIÇÃO,INTERAÇÃO GENE-NUTRIENTE;VALOR BIOLÓGICO DE AL...,Bioquímica da Nutrição,pesquisa,engenharia de aquicultura
43,6809.0,88657608.0,PVA766-2012,Análise da diversidade genética no litoral e i...,Citogenética de peixes;RAPD;Perciformes,88657571.0,2012.0,2010-10-01,2013-03-21,FINALIZADO,EXTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,11.0,GENÉTICA DE RECURSOS MARINHOS,Citogenética;Genética de populações de peixes;;,Genética Animal,pesquisa,biomedicina
44,6809.0,88657608.0,PVA766-2012,Análise da diversidade genética no litoral e i...,Citogenética de peixes;RAPD;Perciformes,88657571.0,2012.0,2010-10-01,2013-03-21,FINALIZADO,EXTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,11.0,GENÉTICA DE RECURSOS MARINHOS,Citogenética;Genética de populações de peixes;;,Genética Animal,pesquisa,ciencias biologicas
45,6809.0,88657608.0,PVA766-2012,Análise da diversidade genética no litoral e i...,Citogenética de peixes;RAPD;Perciformes,88657571.0,2012.0,2010-10-01,2013-03-21,FINALIZADO,EXTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,11.0,GENÉTICA DE RECURSOS MARINHOS,Citogenética;Genética de populações de peixes;;,Genética Animal,pesquisa,ecologia
46,6809.0,88657608.0,PVA766-2012,Análise da diversidade genética no litoral e i...,Citogenética de peixes;RAPD;Perciformes,88657571.0,2012.0,2010-10-01,2013-03-21,FINALIZADO,EXTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,11.0,GENÉTICA DE RECURSOS MARINHOS,Citogenética;Genética de populações de peixes;;,Genética Animal,pesquisa,engenharia de aquicultura
47,8448.0,85142738.0,PVA763-2011,Expressão de Glucagon -Like Peptide-1 (GLP-1) ...,Glicemia pós-prandial;Glucagon-Like-Peptídio 1...,85142720.0,2011.0,2011-08-01,2012-07-31,RENOVADO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,6.0,BIOQUÍMICA DA NUTRIÇÃO,INTERAÇÃO GENE-NUTRIENTE;VALOR BIOLÓGICO DE AL...,Bioquímica da Nutrição,pesquisa,biomedicina
48,8448.0,85142738.0,PVA763-2011,Expressão de Glucagon -Like Peptide-1 (GLP-1) ...,Glicemia pós-prandial;Glucagon-Like-Peptídio 1...,85142720.0,2011.0,2011-08-01,2012-07-31,RENOVADO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,6.0,BIOQUÍMICA DA NUTRIÇÃO,INTERAÇÃO GENE-NUTRIENTE;VALOR BIOLÓGICO DE AL...,Bioquímica da Nutrição,pesquisa,ciencias biologicas
49,8448.0,85142738.0,PVA763-2011,Expressão de Glucagon -Like Peptide-1 (GLP-1) ...,Glicemia pós-prandial;Glucagon-Like-Peptídio 1...,85142720.0,2011.0,2011-08-01,2012-07-31,RENOVADO,INTERNO,Pesquisa Científica,440.0,CENTRO DE BIOCIÊNCIAS,6.0,BIOQUÍMICA DA NUTRIÇÃO,INTERAÇÃO GENE-NUTRIENTE;VALOR BIOLÓGICO DE AL...,Bioquímica da Nutrição,pesquisa,ecologia

In [35]:
df_temp2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201559 entries, 0 to 201558
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              201210 non-null  float64
 1   id_projeto_pesquisa     201210 non-null  float64
 2   codigo_projeto          201210 non-null  object
 3   titulo                  201210 non-null  object
 4   palavras_chave          199039 non-null  object
 5   id_projeto              201210 non-null  float64
 6   ano                     201210 non-null  float64
 7   data_inicio             200924 non-null  object
 8   data_fim                198966 non-null  object
 9   situacao                201210 non-null  object
 10  tipo_projeto            201210 non-null  object
 11  categoria_projeto       201210 non-null  object
 12  id_unidade              201210 non-null  float64
 13  unidade                 201559 non-null  object
 14  id_grupo_pesquisa       163789 non-null  float64
 15  grupo_pesquisa          163295 non-null  object
 16  linha_pesquisa          195169 non-null  object
 17  area_conhecimento_cnpq  197393 non-null  object
 18  classificacao           201210 non-null  object
 19  curso                   196689 non-null  object
dtypes: float64(6), object(14)
memory usage: 30.8+ MB

In [36]:
df_final = pd.concat([df_temp, df_temp2], axis=0, join="outer", ignore_index=True)

In [37]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304384 entries, 0 to 304383
Data columns (total 25 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   titulo                  303349 non-null  object
 1   nome_autor              102139 non-null  object
 2   nome_orientador         102139 non-null  object
 3   curso                   299514 non-null  object
 4   nivel                   102139 non-null  object
 5   tipo_trabalho           83908 non-null   object
 6   ano                     303349 non-null  float64
 7   data_defesa             102139 non-null  object
 8   classificacao           303349 non-null  object
 9   unidade                 304039 non-null  object
 10  Unnamed: 0              201210 non-null  float64
 11  id_projeto_pesquisa     201210 non-null  float64
 12  codigo_projeto          201210 non-null  object
 13  palavras_chave          199039 non-null  object
 14  id_projeto              201210 non-null  float64
 15  data_inicio             200924 non-null  object
 16  data_fim                198966 non-null  object
 17  situacao                201210 non-null  object
 18  tipo_projeto            201210 non-null  object
 19  categoria_projeto       201210 non-null  object
 20  id_unidade              201210 non-null  float64
 21  id_grupo_pesquisa       163789 non-null  float64
 22  grupo_pesquisa          163295 non-null  object
 23  linha_pesquisa          195169 non-null  object
 24  area_conhecimento_cnpq  197393 non-null  object
dtypes: float64(6), object(19)
memory usage: 58.1+ MB

In [38]:
df['curso'].unique()

array(['direito', 'ciencias economicas', 'engenharia ambiental',
       'odontologia',
       'especializacao em gestao de politica de dst, aids hepatites virais e tuberculose',
       'enfermagem', 'engenharia biomedica', 'farmacia', 'servico social',
       'nutricao', 'administracao', 'biblioteconomia', 'ciencias sociais',
       'doutorado em estudos da linguagem', 'mestrado em direito',
       'mestrado em saude coletiva - facisa',
       'mestrado profissional em gestao, trabalho, educacao e saude',
       'mestrado em filosofia',
       'doutorado em ciencia e engenharia de materiais',
       'mestrado profissional em educacao, trabalho e inovacao em medicina',
       'mestrado em ciencia e engenharia de materiais',
       'mestrado em producao animal', 'doutorado em historia',
       'mestrado profissional em inovacao em tecnologias educacionais',
       'mestrado em servico social', 'mestrado em engenharia quimica',
       'mestrado profissional em ensino de ciencias naturais e matematica',
       'doutorado em fisica', 'educacao fisica', 'mestrado em geografia',
       'mestrado em engenharia eletrica e de computacao', 'geologia',
       'residencia em tecnologia da informacao - tre/rn - turma 4',
       'mestrado profissional em tecnologia da informacao',
       'doutorado em administracao', 'doutorado em ciencias da saude',
       'doutorado em ciencias odontologicas',
       'mestrado em educacao fisica', 'mestrado em saude coletiva',
       'mestrado em geodinamica e geofisica',
       'mestrado em ciencia e engenharia de petroleo',
       'doutorado profissional em saude da familia', 'ciencias contabeis',
       'historia', 'filosofia', 'mestrado em ciencias climaticas',
       'sistemas de informacao', 'doutorado em ciencias farmaceuticas',
       'mestrado profissional em educacao especial',
       'mestrado profissional em gestao e inovacao em saude',
       'especializacao em turismo responsavel',
       'mestrado em ciencias da reabilitacao', 'engenharia agronomica',
       'mestrado em ciencias contabeis', 'meteorologia',
       'mestrado em ciencias odontologicas', 'mestrado em quimica',
       'mestrado em sistemas e computacao', 'administracao publica',
       'engenharia textil', 'geografia', 'engenharia de producao',
       'pedagogia', 'doutorado em engenharia eletrica e de computacao',
       'mestrado em estudos da linguagem', 'doutorado em fisioterapia',
       'mestrado profissional em gestao da qualidade em servicos de saude',
       'saude coletiva', 'letras - ingles',
       'letras - lingua portuguesa e literaturas',
       'mestrado em neurociencias', 'engenharia civil',
       'doutorado em filosofia', 'ecologia', 'ciencias biologicas',
       'gestao de politicas publicas', 'design', 'engenharia de software',
       'ciencia da computacao', 'turismo', 'biomedicina',
       'bacharelado interdisciplinar em humanidades', 'gestao hospitalar',
       'arquitetura e urbanismo', 'fonoaudiologia',
       'mestrado profissional em praticas de saude e educacao',
       'engenharia mecanica', 'danca', 'ciencias e tecnologia',
       'mestrado profissional em geografia', 'engenharia de aquicultura',
       'musica', 'doutorado em bioquimica e biologia molecular',
       'engenharia de materiais', 'geofisica', 'engenharia de computacao',
       'jornalismo', 'comunicacao social- publicidade e propaganda',
       'fisica', 'letras - lingua espanhola', 'engenharia florestal',
       'fisioterapia', 'engenharia de alimentos',
       'comunicacao social - audiovisual', 'mestrado em bioinformatica',
       'ciencias atuariais', 'comunicacao social',
       'analise e desenvolvimento de sistemas', 'estatistica',
       'engenharia quimica', 'mestrado profissional em energia eletrica',
       'doutorado em geografia', 'especializacao em analises clinicas',
       'teatro', 'mestrado em engenharia de producao',
       'engenharia eletrica', 'especializacao em auditoria do sus',
       'mestrado em nutricao', 'quimica do petroleo',
       'mestrado profissional em artes - profartes',
       'doutorado em enfermagem na atencao a saude', 'artes visuais',
       'mestrado em psicologia', 'doutorado em arquitetura e urbanismo',
       'quimica', 'mestrado profissional em ensino na saude', 'zootecnia',
       'mestrado em administracao', 'mestrado em historia / ceres',
       'mestrado em fonoaudiologia',
       'mestrado profissional em gestao da informacao e do conhecimento',
       'especializacao em mba em inteligencia de dados',
       'mestrado em engenharia mecatronica',
       'doutorado em desenvolvimento e meio ambiente',
       'mestrado em estudos urbanos e regionais',
       'doutorado em ensino de ciencias e matematica',
       'mestrado profissional em gestao de processos institucionais',
       'mestrado profissional em letras', 'mestrado em estudos da midia',
       'doutorado em estudos da midia',
       'mestrado em ciencias farmaceuticas',
       'mestrado em engenharia mecanica',
       'mestrado profissional em quimica - profqui',
       'mestrado em ensino de ciencias e matematica',
       'doutorado em ciencia da computacao',
       'mestrado em geografia - ceres', 'doutorado em psicologia',
       'mestrado em bioquimica e biologia molecular',
       'mestrado em biologia estrutural e funcional',
       'doutorado em ecologia', 'mestrado em fisioterapia',
       'mestrado em matematica aplicada e estatistica',
       'doutorado em saude coletiva',
       'especializacao em treinamento de forca',
       'mestrado em ciencias da saude', 'mestrado em ecologia',
       'especializacao em tecnologia da informacao - tre/rn - turma 4',
       'engenharia de petroleo', 'mestrado em ciencias sociais',
       'doutorado em demografia',
       'mestrado em desenvolvimento e meio ambiente',
       'mestrado em artes cenicas',
       'especializacao em contabilidade e controladoria',
       'doutorado em estudos urbanos e regionais',
       'doutorado em desenvolvimento e inovacao tecnologica em medicamentos',
       'doutorado em quimica', 'doutorado em turismo',
       'doutorado em engenharia quimica',
       'mestrado em engenharia civil e ambiental',
       'aperfeicoamento em didatica e metodo multissensorial no ensino a estudantes com deficiencia visual',
       'doutorado em psicobiologia', 'doutorado em bioinformatica',
       'mestrado em demografia',
       'especializacao em fundamentos linguisticos para o ensino da leitura e da escrita',
       'mestrado em turismo', 'doutorado em antropologia social',
       'mestrado em musica', 'mestrado em biologia parasitaria',
       'mestrado profissional em educacao fisica em rede nacional',
       'mestrado profissional em ensino de fisica em rede nacional',
       'doutorado em biotecnologia',
       'mestrado profissional em ciencia, tecnologia e inovacao',
       'mestrado em antropologia social',
       'especializacao em ensino de ciencias - anos finais do ensino fundamental',
       'mestrado em enfermagem', 'mestrado em ciencias florestais',
       'mestrado em ciencias aplicadas a saude da mulher',
       'mestrado em psicobiologia', 'mestrado em sistematica e evolucao',
       'doutorado em ciencia e engenharia de petroleo',
       'mestrado profissional em matematica em rede nacional',
       'mestrado em arquitetura e urbanismo', 'mestrado em economia',
       'engenharia mecatronica', 'mestrado em educacao',
       'doutorado em ciencias climaticas', 'matematica',
       'mestrado em assistencia farmaceutica em rede',
       'mestrado em engenharia aeroespacial',
       'engenharia de telecomunicacoes',
       'doutorado em geodinamica e geofisica',
       'especializacao em linguistica textual e ensino',
       'especializacao em engenharia de operacoes e gestao de ativos',
       'doutorado em neurociencias', 'doutorado em servico social',
       'mestrado profissional em gestao publica',
       'especializacao em citologia ginecologica oncotica',
       'mestrado profissional em arquitetura, projeto e meio ambiente',
       'mestrado em historia',
       'residencia em tecnologia da informacao - trf5',
       'doutorado em sistematica e evolucao',
       'mestrado profissional em ensino de historia - profhistoria',
       'aperfeicoamento em educacao especial-inclusiva na educacao basica',
       'especializacao em neurociencias aplicada aos negocios',
       'residencia judicial (modulo r1 e r2)',
       'especializacao em enfermagem neonatal e pediatrica',
       'doutorado em ciencias sociais',
       'especializacao em governanca e gestao agil na justica federal',
       'especializacao em fisioterapia cardiorrespiratoria',
       'mestrado em engenharia textil', 'letras',
       'especializacao em gestao ambiental e inteligencia territorial',
       'especializacao em neuropsicologia clinica',
       'especializacao em gestao da jurisdicao inovadora',
       'especializacao em governanca e gestao de pessoas na justica federal',
       'especializacao em urgencia e emergencia em enfermagem',
       'residencia em tecnologia da informacao na area da saude para a liga contra o cancer',
       'especializacao em auditoria em saude',
       'residencia em tecnologia da informacao - tre/rn - turma 3',
       'residencia em tecnologia da informacao - tce/rn',
       'residencia em tecnologia da informacao - tcmrj/imd',
       'residencia em tecnologia da informacao',
       'especializacao em fisioterapia traumato-ortopedica e esportiva - turma 6',
       'especializacao em gestao da inovacao na seguranca publica',
       'especializacao em contabilidade, controladoria e gestao de custos no setor publico',
       'especializacao em linguistica forense',
       'especializacao em logistica',
       'especializacao em ensino de matematica nos anos iniciais do fundamental',
       'residencia em tecnologia da informacao - jfrn',
       'especializacao em neurorreabilitacao',
       'especializacao em saude da familia',
       'especializacao em gestao publica, auditoria e controladoria com foco nas normas internacionais',
       'residencia em tecnologia da informacao - secretaria de estado da administracao do rn',
       'especializacao em economia solidaria e desenvolvimento territorial',
       'mestrado em fisica',
       'especializacao em gestao estrategica de pessoas',
       'especializacao em literatura e ensino',
       'especializacao em negociacao, conciliacao, mediacao e arbitragem',
       'medicina',
       'especializacao em engenharia de seguranca do trabalho',
       'mestrado profissional em saude da familia',
       'especializacao em dermatologia em enfermagem',
       'especializacao em tecnologia da informacao',
       'residencia judicial (modulo r1)',
       'doutorado em engenharia mecanica',
       'especializacao em gestao dinamica de projetos 2023',
       'especializacao em sono',
       'residencia em tecnologia da informacao aplicada a area juridica - turma tce/rn',
       'especializacao em psicomotricidade',
       'especializacao em consciencia corporal, saude e qualidade de vida',
       'especializacao em alfabetizacao + neurociencias: interfaces na educacao integral',
       'mestrado em engenharia civil',
       'especializacao em gestao dinamica de projetos',
       'especializacao em gestao internacional em tecnologia e inovacao',
       'mestrado em engenharia sanitaria e ambiental',
       'doutorado em nanotecnologia farmaceutica',
       'especializacao em neuropsicopedagogia instit e educ espec na perspec da inclusao',
       'residencia em tecnologia da informacao - tre/rn - turma 2',
       'especializacao em informatica na saude',
       'especializacao em engenharia de operacoes',
       'especializacao em biomecanica',
       'especializacao em gestao ambiental',
       'especializacao em administracao publica',
       'especializacao em turismo e desenvolvimento regional',
       'mestrado em ciencias biologicas',
       'residencia em tecnologia da informacao aplicada a area juridica - turma jf',
       'especializacao em analises clinicas e toxicologicas',
       'especializacao em producao de documentarios',
       'especializacao em gestao de processos', 'especializacao em danca',
       'especializacao em lingua latina',
       'residencia em tecnologia da informacao - turma lais',
       'especializacao em preceptoria em saude',
       'especializacao em direito da inovacao tecnologica',
       'gestao de cooperativas',
       'especializacao em gestao em micro e pequenas empresas com foco nas normas internacionais',
       'especializacao em gestao publica, auditoria e controladoria',
       'especializacao em auditoria e controladoria',
       'especializacao em tecnologia da informacao - tce/rn',
       'psicologia',
       'especializacao em ensino de musica em multiplos contextos',
       'especializacao em direito civil e processual civil',
       'especializacao em engenharia de negocios no setor de supermercados',
       'especializacao em saude publica',
       'especializacao em fisioterapia materno-infantil',
       'residencia em tecnologia da informacao - turma nuplam',
       'especializacao em tecnologia da informacao - turma tre/rn',
       'residencia em tecnologia da informacao - turma tre/rn',
       'especializacao em gestao documental',
       'especializacao em fisioterapia traumato-ortopedica e esportiva',
       'especializacao em alfabetizacao e neurociencias: interfaces na educacao integral',
       'especializacao em direito administrativo',
       'especializacao em enfermagem em terapia intensiva neonatal e pediatrica',
       'especializacao em protese dentaria',
       'especializacao em direito tributario',
       'especializacao em dentistica', 'doutorado em patologia oral',
       'especializacao em periodontia',
       'especializacao em fisiologia clinica do exercicio',
       'especializacao em tecnologias educacionais',
       'especializacao em gerontologia', 'especializacao em marketing',
       'especializacao em libras',
       'especializacao em financas corporativas',
       'especializacao em sistemas embarcados para internet das coisas',
       'especializacao em terapia cognitivo-comportamental',
       'residencia em tecnologia da informacao aplicada a area juridica',
       'especializacao em desenvolvimento para dispositivos moveis',
       'especializacao em literatura e cultura do rio grande do norte',
       'especializacao em gestao do trabalho e da educacao na saude',
       'mestrado em patologia oral', 'residencia judicial',
       'especializacao em enfermagem obstetrica - turma iii - rede cegonha',
       'especializacao em gestao estrategica de negocios',
       'doutorado em educacao',
       'especializacao em fisiologia do exercicio: bases teoricas praticas fitness e personal trainer',
       'especializacao em informatica em saude',
       'especializacao em estudos da escrita e ensino',
       'especializacao em aromaterapia',
       'especializacao em treinamento de forca  turma ii',
       'especializacao em geoprocessamento e analise ambiental',
       'especializacao em historia dos sertoes',
       'especializacao em psicomotricidade clinica e escolar',
       'especializacao em cuidados e praticas integrativas em saude',
       'especializacao mba em controladoria, financas e contabilidade no setor publico',
       'especializacao em fisioterapia traumato-ortopedica e desportiva - turma iv',
       'especializacao em leitura e producao de textos',
       'especializacao em ensino de espanhol como lingua estrangeira',
       'especializacao em gestao de projetos',
       'especializacao em auditoria e controladoria contabil',
       'especializacao em big data',
       'especializacao em lingua espanhola, literatura e traducao',
       'especializacao em gestao da tecnologia da informacao',
       'especializacao em ensino e aprendizagem de ingles como lingua estrangeira',
       'especializacao em desenvolvimento de aplicacoes para dispositivos moveis',
       'especializacao em implantodontia',
       'especializacao em biologia molecular aplicada a saude humana',
       'especializacao em mercado de capitais',
       'especializacao em saude coletiva com enfase em saude da familia',
       'especializacao em terapia intensiva em enfermagem',
       'especializacao em cinema',
       'especializacao em programa nacional de educacao, pobreza e desigualdade social',
       'especializacao em literatura na escola',
       'especializacao em gestao de politicas publicas',
       'especializacao em desenvolvimento de sistemas ufrn',
       'especializacao em ensino de sociologia no ensino medio',
       'especializacao em linguistica e ensino de texto',
       'especializacao em estrategias linguistico-discursivas de avaliacao',
       'especializacao em psicologia da saude: desenvolvimento e hospitalizacao',
       'especializacao em gestao de ti',
       'especializacao em direito internacional',
       'especializacao em ensino de filosofia no ensino medio',
       'especializacao em automacao de processos industriais',
       'especializacao em ensino de musica na educacao basica',
       'especializacao em psicologia clinica fenomenologica',
       'especializacao em historia e cultura afro-brasileira e africana',
       'mestrado profissional em design',
       'especializacao em geoprocessamento e cartografia digital',
       'especializacao em ensino de matematica',
       'especializacao em historia e cultura africana e afro-brasileira',
       'especializacao em gestao escolar',
       'especializacao em fisioterapia traumato-ortopedica e desportiva - turma iii',
       'especializacao em propaganda e marketing na gestao de marcas',
       'especializacao em controladoria governamental',
       'especializacao em ensino de portugues e linguistica',
       'especializacao em manejo sustentavel do semiarido',
       'especializacao em docencia na educacao infantil', 'aquicultura',
       'gestao publica', 'especializacao em literatura afro-brasileira',
       'especializacao em planejamento tributario - curso ii',
       'especializacao em ensino-aprendizagem de lingua portuguesa',
       'especializacao em arquitetura de nuvem',
       'especializacao em gestao ambiental costeira',
       'especializacao em audiologia',
       'especializacao em educacao em direitos humanos',
       'especializacao em gestao industrial',
       'especializacao em fisioterapia traumato-ortopedica e desportiva - turma ii',
       'especializacao em educacao ambiental para escolas sustentaveis',
       'especializacao em ciencias atuariais e demografia',
       'especializacao em direito constitucional',
       'residencia em engenharia de software',
       'especializacao em gestao publica para ministerio publico do rio grande do norte',
       'especializacao em inteligencia e analise estrategica de negocios',
       'especializacao em arqueologia do nordeste brasileiro',
       'especializacao inic. esportiva:bases fisiologicas pedagogicas no desenv. humano',
       'especializacao  em direito internacional - curso iv',
       'especializacao em psicologia do trabalho e das organizacoes',
       'especializacao em metalurgia da fundicao',
       'especializacao em financas',
       'especializacao em literatura brasileira - celb',
       'especializacao em gestao em saude',
       'especializacao em estudos sobre a linguagem: teorias e ensino (esteio)',
       'especializacao em ensino de artes na educacao basica: musica',
       'especializacao em ensino e aprendizagem de linguas',
       'especializacao em gestao estrategica de sistemas de informacao',
       'especializacao em coordenacao pedagogica',
       'doutorado em ciencias contabeis (unb-ufrn-ufpb)',
       'especializacao em prevencao ao uso do alcool e outras drogas',
       'mestrado em ciencias contabeis (unb-ufrn-ufpb)',

In [39]:
df_final.to_csv(
    'dataset_concat1.0.csv',
    sep=';',
     encoding='utf-8',
    index=False
)

ta dando valores absurdos e vi que quando eu junto porque quando deu merge pelo curso, ele associou a cada uma das unidades que tinham o mesmo nome do cuso. ex>: administracao esta duplicado todos os trabalhos pq tem adm no campus natal mas tem no campus caicó tbm. como a analise seria da ufrn de maneira geral, nao teria problema passar a régua nas duplicatas, ne?