In [11]:
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df_unidades_curso = pd.read_csv('../unidades_academicas/unidades_e_cursos.csv', sep=';')
df_tccs = pd.read_csv('../TCC/tccs_tratado3.0.csv', sep=';')
df_pesquisa = pd.read_csv('../projetos-de-pesquisa-limpo2.0.csv')

In [17]:
df_tccs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84893 entries, 0 to 84892
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   titulo           84893 non-null  object
 1   nome_autor       84893 non-null  object
 2   nome_orientador  84893 non-null  object
 3   curso            84893 non-null  object
 4   nivel            84893 non-null  object
 5   tipo_trabalho    67045 non-null  object
 6   ano              84893 non-null  float64
 7   data_defesa      84893 non-null  object
 8   classificacao    84893 non-null  object
dtypes: float64(1), object(8)
memory usage: 5.8+ MB

In [ ]:
df_unidades_curso.info()

In [18]:
df_pesquisa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21382 entries, 0 to 21381
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              21382 non-null  int64
 1   id_projeto_pesquisa     21382 non-null  int64
 2   codigo_projeto          21382 non-null  object
 3   titulo                  21382 non-null  object
 4   palavras_chave          21130 non-null  object
 5   id_projeto              21382 non-null  int64
 6   ano                     21382 non-null  int64
 7   data_inicio             21351 non-null  object
 8   data_fim                21121 non-null  object
 9   situacao                21382 non-null  object
 10  tipo_projeto            21382 non-null  object
 11  categoria_projeto       21382 non-null  object
 12  id_unidade              21382 non-null  int64
 13  unidade                 21382 non-null  object
 14  id_grupo_pesquisa       17636 non-null  float64
 15  grupo_pesquisa          17597 non-null  object
 16  linha_pesquisa          20721 non-null  object
 17  area_conhecimento_cnpq  20971 non-null  object
 18  classificacao           21382 non-null  object
dtypes: float64(1), int64(5), object(13)
memory usage: 3.1+ MB

In [19]:
for df in [df_unidades_curso, df_tccs]:
    df["curso"] = (df["curso"] #padronizar
                   .astype(str)
                   .str.strip()
                   .str.lower()
                   .str.normalize("NFKD")
                   .str.encode("ascii", errors="ignore")
                   .str.decode("utf-8"))

df_temp = pd.merge(df_tccs, df_unidades_curso, on="curso", how="outer")

df_temp.head()

,titulo,nome_autor,nome_orientador,curso,nivel,tipo_trabalho,ano,data_defesa,classificacao,id_curso,id_unidade,unidade
0,NaN,NaN,NaN,aaa,NaN,NaN,NaN,NaN,NaN,150845958.0,31011.0,"FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOC..."
1,explorando o potencial das finanças verdes: um...,ana flavia eufrasio de lima,israel josé dos santos felipe,administracao,graduação,monografia,2024.0,2025/11/25 00:00:00.000,tcc,2000002.0,443.0,CENTRO DE CIÊNCIAS SOCIAIS APLICADAS
2,explorando o potencial das finanças verdes: um...,ana flavia eufrasio de lima,israel josé dos santos felipe,administracao,graduação,monografia,2024.0,2025/11/25 00:00:00.000,tcc,2000004.0,31011.0,"FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOC..."
3,indicadores de desempenho: um estudo da perspe...,alvaro araujo de medeiros,marconi neves macedo,administracao,graduação,monografia,2025.0,2025/09/09 00:00:00.000,tcc,2000002.0,443.0,CENTRO DE CIÊNCIAS SOCIAIS APLICADAS
4,indicadores de desempenho: um estudo da perspe...,alvaro araujo de medeiros,marconi neves macedo,administracao,graduação,monografia,2025.0,2025/09/09 00:00:00.000,tcc,2000004.0,31011.0,"FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOC..."

In [20]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145739 entries, 0 to 145738
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   titulo           144960 non-null  object
 1   nome_autor       144960 non-null  object
 2   nome_orientador  144960 non-null  object
 3   curso            145739 non-null  object
 4   nivel            144960 non-null  object
 5   tipo_trabalho    126729 non-null  object
 6   ano              144960 non-null  float64
 7   data_defesa      144960 non-null  object
 8   classificacao    144960 non-null  object
 9   id_curso         145571 non-null  float64
 10  id_unidade       145571 non-null  float64
 11  unidade          145571 non-null  object
dtypes: float64(3), object(9)
memory usage: 13.3+ MB

In [21]:
df_temp2 = pd.merge(df_pesquisa, df_unidades_curso, on="id_unidade", how="outer")

df_temp2.head(50)

,Unnamed: 0,id_projeto_pesquisa,codigo_projeto,titulo,palavras_chave,id_projeto,ano,data_inicio,data_fim,situacao,...,id_unidade,unidade_x,id_grupo_pesquisa,grupo_pesquisa,linha_pesquisa,area_conhecimento_cnpq,classificacao,id_curso,curso,unidade_y
0,16653.0,38288.0,PIM725-2005,O estudo da canção: o uso de metodologias coad...,expressividade artística;corporeidade total na...,38288.0,2005.0,2005-05-01,2005-05-01,FINALIZADO,...,-1,NÃO INFORMADA,1.0,ISOLADO,metodologia de ensino de canto;método de ações...,Música,pesquisa,NaN,NaN,NaN
1,17573.0,37722.0,PIM80-2004,Platero y yo - construção da performance,processos de estudo em música;atmosferas;motivos,37722.0,2004.0,2004-05-01,2005-03-01,FINALIZADO,...,-1,NÃO INFORMADA,NaN,NaN,NaN,Música,pesquisa,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,100300443.0,especializacao em desenvolvimento de sistemas ...,SUPERINTENDÊNCIA DE TECNOLOGIA DA INFORMAÇÃO
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,100350606.0,especializacao em gestao de ti,SUPERINTENDÊNCIA DE TECNOLOGIA DA INFORMAÇÃO
4,9326.0,85064491.0,PVG5514-2011,Desenvolvimento de um sensor dinâmico para pró...,"Plasma, IPMC, Polímero ionico, sensor e atuado...",85064478.0,2011.0,2011-08-01,2012-07-31,EM EXECUÇÃO,...,3,PRÓ-REITORIA DE GRADUAÇÃO,75.0,PROCESSAMENTO DE MATERIAIS POR PLASMA,Bioengenharia,Bioengenharia,pesquisa,NaN,NaN,NaN
5,9327.0,85101352.0,PVG5515-2011,Uso da técnica de Moiré de projeção para mediç...,Bioengenharia; Reabilitação; Eng. Computacional,85101339.0,2011.0,2011-08-01,2012-07-31,EM EXECUÇÃO,...,3,PRÓ-REITORIA DE GRADUAÇÃO,22.0,MECÂNICA COMPUTACIONAL,Projetos Mecânicos / Bioengenharia,Bioengenharia,pesquisa,NaN,NaN,NaN
6,11316.0,2239016.0,PVG4911-2010,Análise e Projeto de Superfícies Seletivas em ...,"Superfície seletiva em freqüência, resposta mu...",2239014.0,2010.0,2010-08-01,2011-07-31,EM EXECUÇÃO,...,3,PRÓ-REITORIA DE GRADUAÇÃO,16.0,GRUPO DE MICROONDAS E ANTENAS,Estruturas de transmissão planares,Telecomunicações,pesquisa,NaN,NaN,NaN
7,11355.0,2519559.0,PVG5514-2010,Desenvolvimento de um sensor dinâmico para pró...,"Plasma, IPMC, Polímero ionico, sensor e atuado...",2519542.0,2010.0,2010-08-01,2011-07-31,RENOVADO,...,3,PRÓ-REITORIA DE GRADUAÇÃO,75.0,PROCESSAMENTO DE MATERIAIS POR PLASMA,Bioengenharia,Bioengenharia,pesquisa,NaN,NaN,NaN
8,11356.0,2519952.0,PVG5515-2010,Uso da técnica de Moiré de projeção para mediç...,Bioengenharia; Reabilitação; Eng. Computacional,2519939.0,2010.0,2010-08-01,2011-07-31,RENOVADO,...,3,PRÓ-REITORIA DE GRADUAÇÃO,22.0,MECÂNICA COMPUTACIONAL,Projetos Mecânicos / Bioengenharia,Bioengenharia,pesquisa,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,NaN,NaN,NaN,NaN,NaN,NaN,150841326.0,especializacao em linguas estrangeiras para in...,DDP/PROGESP - DIRETORIA DE DESENVOLVIMENTO DE ...
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,NaN,NaN,NaN,NaN,NaN,NaN,101080278.0,programa de capacitacao e qualificacao,DDP/PROGESP - DIRETORIA DE DESENVOLVIMENTO DE ...
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,NaN,NaN,NaN,NaN,NaN,NaN,97114483.0,z- outros,DDP/PROGESP - DIRETORIA DE DESENVOLVIMENTO DE ...
12,8691.0,85175079.0,PVC5458-2011,AS ESTRATÉGIAS POLÍTICO-ELEITORIAIS E AS CONTR...,"eleições, partidos políticos, propaganda eleit...",85175066.0,2011.0,2011-08-01,2012-07-31,EM EXECUÇÃO,...,16,PROPLAN - SECRETARIA ADMINISTRATIVA,53.0,"CULTURA, POLÍTICA E EDUCAÇÃO","Política, Democracia e Sociedade",Estudos Eleitorais e Partidos Políticos,pesquisa,NaN,NaN,NaN
13,10588.0,2434006.0,PVC5458-2010,AS ESTRATÉGIAS POLÍTICO-ELEITORIAIS E AS CONTR...,"eleições, partidos políticos, propaganda eleit...",2434004.0,2010.0,2010-08-01,2011-07-31,RENOVADO,...,16,PROPLAN - SECRETARIA ADMINISTRATIVA,53.0,"CULTURA, POLÍTICA E EDUCAÇÃO","Política, Democracia e Sociedade",Estudos Eleitorais e Partidos Políticos,pesquisa,NaN,NaN,NaN
14,7117.0,90693052.0,PVC6167-2012,"MÍDIA, CORPO E CIDADE: Comunicação urbana e ex...",Midia - corpo - cidade - subjetividade - imagem,90693025.0,2012.0,2013-08-01,2014-07-31,FINALIZADO,...,19,SUPERINTENDENCIA DE COMUNICACAO,97750794.0,Marginália - Grupo de Estudos Transdisciplinar...,"Comunicação urbana, corpo, estética e imagem.",Teoria da Comunicação,pesquisa,NaN,NaN,NaN
15,10595.0,2736702.0,PVC5620-2010,Interatividade em Videobox - Linguagens e técn...,Produção - Conteúdos audiovisuais - Internet -...,2736700.0,2010.0,2010-01-01,2010-12-31,FINALIZADO,...,19,SUPERINTENDENCIA DE COMUNICACAO,122.0,GRUPO DE ESTUDOS DA COMPLEXIDADE-GRECOM,Estratégia do Pensamento e Produção do Conheci...,Radiodifusão,pesquisa,NaN,NaN,NaN
16,10596.0,2806296.0,PVC5627-2010,Ações em Comunicação Social nas Mídias Univers...,"Comunicação Social, divulgação científica, dif...",2806294.0,2010.0,2009-09-20,2010-11-20,FINALIZADO,...,19,SUPERINTENDENCIA DE COMUNICACAO,122.0,GRUPO DE ESTUDOS DA COMPLEXIDADE-GRECOM,Corpus,Radiodifusão,pesquisa,NaN,NaN,NaN
17,10626.0,4888438.0,PVC6167-2010,"MÍDIA, CORPO E CIDADE: Comunicação urbana e ex...",Midia - corpo - cidade - subjetividade - imagem,4888436.0,2010.0,2011-01-01,2011-12-31,FINALIZADO,...,19,SUPERINTENDENCIA DE COMUNICACAO,146.0,GEMINI - Grupo de Estudos de Mídia - Análises ...,Corpus,Teoria da Comunicação,pesquisa,NaN,NaN,NaN
18,11030.0,2054706.0,PVE2934-2010,Análise Webométrica dos Sítios das Universidad...,"Webometria, Estudos métricos da informação, in...",2054677.0,2010.0,2010-02-06,2011-02-05,FINALIZADO,...,21,BIBLIOTECA CENTRAL ZILA MAMEDE,5242392.0,INFORMAÇÃO NA SOCIEDADE CONTEMPORÂNEA,Estudos Métricos da Informação em CT&I,Ciência da Informação,pesquisa,NaN,NaN,NaN
19,11031.0,2054854.0,PVE2935-2010,Análise webométrica dos sítios das instituiçõe...,"Estudos Métricos da Informação, Webometria, Ci...",2054805.0,2010.0,2010-02-06,2011-02-05,FINALIZADO,...,21,BIBLIOTECA CENTRAL ZILA MAMEDE,5242392.0,INFORMAÇÃO NA SOCIEDADE CONTEMPORÂNEA,Estudos Métricos da Informação em CT&I,Ciência da Informação,pesquisa,NaN,NaN,NaN
20,12709.0,11146683.0,PVE2934-2009,Análise Webométrica dos Sítios das Universidad...,"Webometria, Estudos métricos da informação, in...",11146683.0,2009.0,2008-04-29,2009-10-29,RENOVADO,...,21,BIBLIOTECA CENTRAL ZILA MAMEDE,5242392.0,INFORMAÇÃO NA SOCIEDADE CONTEMPORÂNEA,Estudos Métricos da Informação em CT&I,Ciência da Informação,pesquisa,NaN,NaN,NaN
21,12710.0,11150810.0,PVE2935-2009,Análise webométrica dos sítios das instituiçõe...,"Estudos Métricos da Informação, Webometria, Ci...",11150810.0,2009.0,2007-12-01,2009-11-30,RENOVADO,...,21,BIBLIOTECA CENTRAL ZILA MAMEDE,5242392.0,INFORMAÇÃO NA SOCIEDADE CONTEMPORÂNEA,Estudos Métricos da Informação em CT&I,Ciência da Informação,pesquisa,NaN,NaN,NaN
22,88.0,129554320.0,PIB15894-2018,Novas distribuições de probabilidade contínuas...,Novas distribuições de probabilidade contínuas...,91819646.0,2018.0,2018-08-01,2019-07-31,FINALIZADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,Novas distribuições de probabilidade contínuas,Teoria Geral e Fundamentos da Probabilidade,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
23,343.0,128932568.0,PVB15216-2018,Aprimoramento de métodos inferenciais em algum...,"Bootstrap, correção de Bartlett, correção tipo...",91818329.0,2018.0,2018-08-01,2019-07-31,FINALIZADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Teoria assintótica,Probabilidade e Estatística,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
24,347.0,129400669.0,PVB15288-2018,Um estudo dos modelos da urna de Pólya,"Urna de Pólya, distribuição de probabilidade, ...",91819055.0,2018.0,2018-08-01,2019-07-31,EM EXECUÇÃO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Novas distribuições de probabilidade,Teoria Geral e Fundamentos da Probabilidade,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
25,353.0,129431215.0,PVB15357-2018,Tamanho amostral em modelos para sobredispersão,modelos lineares generalizados; critério da co...,91819140.0,2018.0,2018-08-01,2019-07-31,EM EXECUÇÃO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Modelos de regressão,Inferência Paramétrica,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
26,357.0,129325405.0,PVB15395-2018,Ferramentas Gráficas de Diagnóstico para Model...,"regressão, análise de dados, modelagem",91818864.0,2018.0,2018-08-01,2021-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Modelos de regressão,Regressão e Correlação,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
27,368.0,129493384.0,PVB15589-2018,PACOTE GEOESTATISTICO PARA PROCESSOS DE CONTAG...,"Modelo espacial, Processos de Poisson Não Homo...",91819393.0,2018.0,2018-08-01,2020-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Estatistica Espacial,Probabilidade e Estatística Aplicadas,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
28,379.0,129516225.0,PVB15750-2018,Melhoria de Qualidade de Informações Meteoroló...,Chikungunya; dengue; doenças infecciosas; muda...,91819508.0,2018.0,2018-01-01,2020-05-31,EM EXECUÇÃO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Análise de dados,Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
29,395.0,130133276.0,PVB15998-2018,Ferramenta de Pesquisa e Análise de Pedidos de...,"transparência, políticas públicas, estatística...",91820165.0,2018.0,2018-08-01,2021-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,BASE DE PESQUISA EM MÉTODOS ESTATÍSTICOS,Astrofísica Estelar,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
30,979.0,123640578.0,PIB14347-2017,Uma análise de sobrevida de pacientes com cânc...,Câncer de Colo do Útero; Sobrevida; Fatores Pr...,91813973.0,2017.0,2017-08-01,2019-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,Análise de sobrevida de pacientes com câncer d...,Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
31,985.0,123771509.0,PIB14634-2017,Validação dos cenários de mudanças climáticas ...,"Projeções Climáticas, AR5, IPCC, Nordeste bra...",91814229.0,2017.0,2017-08-01,2022-08-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,Climatologia,Climatologia,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
32,992.0,124123396.0,PIB14851-2017,Calibração de dados imputados para estimação e...,métodos estatísticos; amostragem complexa; err...,91814673.0,2017.0,2017-08-01,2021-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,"Estatística recursiva, estimação baysiana",Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
33,993.0,124123446.0,PIB14852-2017,Uso de indicadores de acurácia para corrigir e...,métodos estatísticos; amostragem complexa; err...,91814674.0,2017.0,2017-08-01,2021-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,"Estatística recursiva, estimação bayesiana",Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
34,1248.0,121935464.0,PVB13862-2017,ANÁLISE DA COMPETÊNCIA DE UNIDADES JUDICIÁRIAS...,Banco de Dados; Competência Judicial; Dimensio...,91811999.0,2017.0,2017-02-01,2018-07-31,EM EXECUÇÃO,...,47,DEPARTAMENTO DE ESTATISTICA,99064429.0,Grupo de Pesquisa em Estudos Organizacionais,"Estudos multidisciplinares em Estatística, TI,...",Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
35,1265.0,123526441.0,PVB14137-2017,Um estudo sobre as cadeias estocásticas com me...,"processos estocásticos, cadeias estocásticas c...",91813667.0,2017.0,2017-08-01,2019-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Processos estocásticos,Probabilidade,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
36,1267.0,123523619.0,PVB14142-2017,Abordagem computacional para aperfeiçoamento d...,Bootstrap; Correção de Bartlett; Estatística d...,91813661.0,2017.0,2017-08-01,2018-07-31,EM EXECUÇÃO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Modelos de regressão,Inferência Paramétrica,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
37,1292.0,123764328.0,PVB14526-2017,Modelo Geoestatistico t multivariado,"Modelo Geoestatistico, Distribuição t multivar...",91814205.0,2017.0,2017-08-01,2018-07-31,FINALIZADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Modelos de regressão,Inferência Paramétrica,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
38,2270.0,117216863.0,PVB12892-2016,Combinação de Modelos de Previsão Climática,"previsão climática, aquecimento global, combin...",91808456.0,2016.0,2016-08-01,2018-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Modelos de regressão,Regressão e Correlação,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
39,2276.0,117580168.0,PVB12951-2016,Novos modelos para séries temporais de valores...,"Séries de contagem, operador thinning, modelag...",91808668.0,2016.0,2016-08-01,2020-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Séries Temporais,Inferência em Processos Estocásticos,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
40,2284.0,117628832.0,PVB13090-2016,Previsão no processo PSINAR(1),Previsão. Processos PSINAR(1). Séries Temporai...,91808759.0,2016.0,2018-08-01,2019-07-31,FINALIZADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Séries Temporais,Inferência em Processos Estocásticos,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
41,2316.0,117765861.0,PVB13575-2016,Explorando o sistema complexo de incidência e ...,mudanças climáticas; Zika; dengue; Chikungunya...,91809329.0,2016.0,2016-08-01,2021-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Análise de dados,Estatística,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
42,2328.0,120776768.0,PVB13713-2016,Modelo Geoestatistico de Poisson Aplicado a Da...,"Modelo Geoestatistico,Processo Poisson não hom...",91811265.0,2016.0,2017-01-01,2017-12-31,FINALIZADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Estatistica Espacial,Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
43,2331.0,121064367.0,PVB13827-2016,Melhoria de Qualidade de Informações Meteoroló...,modelagem; mudanças climáticas; planejamento d...,91811508.0,2016.0,2017-01-01,2018-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Análise de dados,Planejamento de Experimentos,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
44,2934.0,110233071.0,PIB12107-2015,Uma análise espacial e de tendências dos coefi...,Câncer; Colo do útero; Tendência,91804629.0,2015.0,2015-08-01,2017-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,Mortalidade por câncer,Probabilidade e Estatística Aplicadas,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
45,3130.0,110212517.0,PVB12090-2015,Modelos Lineares Generalizados para Análise de...,"modelos lineares generalizados, delineamento d...",91804592.0,2015.0,2015-08-01,2017-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Modelos de regressão,Regressão e Correlação,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
46,3159.0,110334033.0,PVB12344-2015,Métodos Estatísticos inovadores no Controle Es...,"gráficos de controle multivariado, processos a...",91804915.0,2015.0,2015-08-01,2017-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,911651.0,Base de Pesquisa em Métodos Estatísticos,Controle Estatístico de Qualidade,Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
47,3670.0,100641851.0,PIB10447-2014,Uma análise espacial e de tendências dos coefi...,Câncer de boca; câncer de orofaringe; mortalidade,91797904.0,2014.0,2014-01-01,2016-12-31,FINALIZADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,Mortalidade por câncer,Probabilidade e Estatística Aplicadas,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
48,3698.0,104919975.0,PIB11811-2014,ANÁLISE RETROSPECTIVA E PROSPECTIVA DA DEMANDA...,"demanda judicial, modelo organizacional, análi...",91801240.0,2014.0,2014-12-01,2016-11-30,EM EXECUÇÃO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,"Estatística aplicada, demografia, estudos orga...",Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA
49,3700.0,110504880.0,PIB12429-2014,Calibração de dados imputados para estimação e...,População finita; pesquisa por amostragem; dad...,91805067.0,2014.0,2014-01-01,2017-07-31,RENOVADO,...,47,DEPARTAMENTO DE ESTATISTICA,NaN,NaN,Amostragem,Análise de Dados,pesquisa,138156167.0,especializacao em ciencia de dados,DEPARTAMENTO DE ESTATISTICA

In [22]:
df_temp2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265685 entries, 0 to 265684
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              265313 non-null  float64
 1   id_projeto_pesquisa     265313 non-null  float64
 2   codigo_projeto          265313 non-null  object
 3   titulo                  265313 non-null  object
 4   palavras_chave          262423 non-null  object
 5   id_projeto              265313 non-null  float64
 6   ano                     265313 non-null  float64
 7   data_inicio             264971 non-null  object
 8   data_fim                262330 non-null  object
 9   situacao                265313 non-null  object
 10  tipo_projeto            265313 non-null  object
 11  categoria_projeto       265313 non-null  object
 12  id_unidade              265685 non-null  int64
 13  unidade_x               265313 non-null  object
 14  id_grupo_pesquisa       217910 non-null  float64
 15  grupo_pesquisa          217279 non-null  object
 16  linha_pesquisa          257218 non-null  object
 17  area_conhecimento_cnpq  260450 non-null  object
 18  classificacao           265313 non-null  object
 19  id_curso                260813 non-null  float64
 20  curso                   260813 non-null  object
 21  unidade_y               260813 non-null  object
dtypes: float64(6), int64(1), object(15)
memory usage: 44.6+ MB

In [16]:
df_final = pd.concat([df_temp, df_temp2], axis=0, join="outer", ignore_index=True)